version: '3.8'

services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROFRONTEND: shell
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MICROFRONTEND=shell
      - SHELL_URL=http://localhost:3000
      - USER_MANAGEMENT_URL=http://localhost:3001
      - PERMISSION_CONTROL_URL=http://localhost:3002
      - WORKFLOW_MANAGEMENT_URL=http://localhost:3003
      - BIGQUERY_URL=http://localhost:3004
    depends_on:
      - user-management
      - permission-control
      - workflow-management
      - bigquery

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROFRONTEND: user-management
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MICROFRONTEND=user-management
      - SHELL_URL=http://localhost:3000

  permission-control:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROFRONTEND: permission-control
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - MICROFRONTEND=permission-control
      - SHELL_URL=http://localhost:3000

  workflow-management:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROFRONTEND: workflow-management
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - MICROFRONTEND=workflow-management
      - SHELL_URL=http://localhost:3000

  bigquery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MICROFRONTEND: bigquery
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - MICROFRONTEND=bigquery
      - SHELL_URL=http://localhost:3000

networks:
  default:
    name: microfrontend-network
